version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      - database_client=mysql
      - database_connection_host=db
      - database_connection_user=root
      - database_connection_password=1234
      - database_connection_database=.ghost
    depends_on:
      - db
    networks:
      - my-network
  
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:

